// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YLBaseMessageModel.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "YlbaseMessageModel.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - YlbaseMessageModelRoot

@implementation YlbaseMessageModelRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - YlbaseMessageModelRoot_FileDescriptor

static GPBFileDescriptor *YlbaseMessageModelRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - YLBaseMessageModel

@implementation YLBaseMessageModel

@dynamic title;
@dynamic module;
@dynamic command;
@dynamic data_p;

typedef struct YLBaseMessageModel__storage_ {
  uint32_t _has_storage_[1];
  int32_t title;
  int32_t module;
  int32_t command;
  NSData *data_p;
} YLBaseMessageModel__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = YLBaseMessageModel_FieldNumber_Title,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(YLBaseMessageModel__storage_, title),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "module",
        .dataTypeSpecific.className = NULL,
        .number = YLBaseMessageModel_FieldNumber_Module,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(YLBaseMessageModel__storage_, module),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "command",
        .dataTypeSpecific.className = NULL,
        .number = YLBaseMessageModel_FieldNumber_Command,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(YLBaseMessageModel__storage_, command),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "data_p",
        .dataTypeSpecific.className = NULL,
        .number = YLBaseMessageModel_FieldNumber_Data_p,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(YLBaseMessageModel__storage_, data_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[YLBaseMessageModel class]
                                     rootClass:[YlbaseMessageModelRoot class]
                                          file:YlbaseMessageModelRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(YLBaseMessageModel__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
