// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YLMessageModel.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class YLUserModel;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - YlmessageModelRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface YlmessageModelRoot : GPBRootObject
@end

#pragma mark - YLUserModel

typedef GPB_ENUM(YLUserModel_FieldNumber) {
  YLUserModel_FieldNumber_UserId = 1,
  YLUserModel_FieldNumber_Name = 2,
  YLUserModel_FieldNumber_Avatar = 3,
};

/**
 * 用户单聊信息模型
 **/
@interface YLUserModel : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

#pragma mark - YLMessageModel

typedef GPB_ENUM(YLMessageModel_FieldNumber) {
  YLMessageModel_FieldNumber_FromUser = 1,
  YLMessageModel_FieldNumber_ToUser = 2,
  YLMessageModel_FieldNumber_MessageType = 3,
  YLMessageModel_FieldNumber_TextString = 4,
  YLMessageModel_FieldNumber_MessageSource = 5,
  YLMessageModel_FieldNumber_VoiceLength = 6,
  YLMessageModel_FieldNumber_VoiceData = 7,
  YLMessageModel_FieldNumber_Token = 8,
  YLMessageModel_FieldNumber_MessageId = 9,
};

/**
 * 用户单聊信息模型
 **/
@interface YLMessageModel : GPBMessage

/** 发送人 */
@property(nonatomic, readwrite, strong, null_resettable) YLUserModel *fromUser;
/** Test to see if @c fromUser has been set. */
@property(nonatomic, readwrite) BOOL hasFromUser;

/** 送达人 */
@property(nonatomic, readwrite, strong, null_resettable) YLUserModel *toUser;
/** Test to see if @c toUser has been set. */
@property(nonatomic, readwrite) BOOL hasToUser;

/** 消息类型 */
@property(nonatomic, readwrite) uint32_t messageType;

/** 消息字符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *textString;

/** 消息资源地址（如图片、视频、文件） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageSource;

/** 录音时长 */
@property(nonatomic, readwrite) uint32_t voiceLength;

/** 录音数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *voiceData;

/** token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
