source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
 platform :ios, ‘8.0’


target ‘YLScoketTest’ do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'CocoaAsyncSocket'
    pod 'SocketRocket'
    pod 'MQTTKit'
    pod 'Masonry'
    #pod 'MBProgressHUD'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'FMDB'
    pod 'SDWebImage'
    pod 'SSKeychain'
    pod 'YYModel'
    #pod 'SWTableViewCell'
    pod 'QBImagePickerController'
    #pod 'ProtocolBuffers'
    #pod 'ChatKit'
    pod 'ReactiveObjC'
    pod 'IQKeyboardManager'
    
end
