
# Uncomment this line to define a global platform for your project
 platform :ios, ‘8.0’


target ‘YLScoketTest’ do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'CocoaAsyncSocket'
    pod 'SocketRocket'
    pod 'MQTTKit'
    pod 'Masonry'
    pod 'Masonry'
    pod 'MBProgressHUD'
    #pod 'ChatKit'
    
end
